account/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('company_profile', views.companyProfile, name='company_profile'),
    path('company_profile/<int:id>',views.editcompany, name='editcompany'),
    path('profile', views.profile, name='profile'),
    path('profile/<int:id>',views.editprofile, name='edit')
]

jobboard/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name='post'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:pk>/', views.post_detail, name="post_detail"),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('FindJob', views.FindJob, name='FindJob'),
    path('createPost',views.createPost, name='createPost'),
    path('update_post/<str:pk>/', views.updatePost, name="update_post"),
    path('delete_post/<str:pk>/', views.deletePost, name="delete_post"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('jobboard.urls')),
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- HOME -->
    <section class="section-hero overlay inner-page bg-image" style="background-image: url('static/images/hero_1.jpg');" id="home-section">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h1 class="text-white font-weight-bold">บทความที่น่าสนใจ</h1>
            <div class="custom-breadcrumbs">
              <a href="#">Home</a> <span class="mx-2 slash">/</span>
              
            </div>
          </div>
        </div>
      </div>
    </section>


     
    <section class="site-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 text-center" data-aos="fade">
            <h2 class="section-title mb-3">บทความที่น่าสนใจเกี่ยวกับงาน IT</h2>
          </div>
        </div>
        <div class="row align-items-center block__69944">

          <div class="col-md-6">
              <img src="https://cdn.pixabay.com/photo/2016/07/25/09/35/styles-1540167_1280.jpg"  width="80%" hight="80%" alt="Image" class="img-fluid mb-4 rounded">
          </div>

          <div class="col-md-6">
            <h3>10 แนวทางเพื่อการออกแบบ Database ให้ดีที่สุด</h3>
            <p class="text-muted">29/01/2020</p>
            <p>Database เป็นองค์ประกอบสำคัญของ Applications และ Computers ด้วยเหตุที่มันเก็บข้อมูลที่จำเป็นและสำคัญ ดังนั้น</p>           
              <a href="https://www.techstarthailand.com/blog/detail/10-Best-Database-Design-Practices/1176">Read more..</a>
          </div>
          
          <br>
          <br>
          <div class="col-md-6">
            <img src="static/images/pgg_2.jpg" alt="Image" class="img-fluid mb-4 rounded">
          </div>
          <div class="col-md-6">
            <h3>10 ปัจจัยที่ใช้เลือกภาษา Programming และ Frameworks ให้เหมาะกับ Project</h3>
            <p class="text-muted">29/01/2020</p>
            <p>เมื่อคุณเริ่ม Software Project ใหม่ แน่นอนว่าคุณมีตัวเลือกมากมายให้เลือกใช้ สิ่งสำคัญคือการเลือกสิ่งที่เหมาะสมกับ</p>
            <a href="https://www.techstarthailand.com/blog/detail/The-Right-Programming-Languages-and-Frameworks-for-Your-Project/1175"></a>
          </div>

          <div class="col-md-6">
            <img src="static/images/pgg_3.jpg" alt="Image" class="img-fluid mb-4 rounded">
          </div>

          <div class="col-md-6">
            <h3>20 VS Code Shortcuts ที่ช่วยให้คุณ Coding ได้เร็วขึ้น</h3>
            <p class="text-muted">29/01/2020</p>
            <p>ไม่ใช่ทุกคนที่มีเวลามากพอที่เรียนรู้เทคนิคและเคล็ดลับในการค้นหาสิ่งที่จะช่วยให้พวกเขาเขียน Code ได้เร็วขึ้นซึ่งพวกมันมี</p>
            <div class="social mt-4">             
              <a href="https://www.techstarthailand.com/blog/detail/20-VS-Code-Shortcuts-for-Faster-Coding/1174"><span class="icon-linkedin"></span></a>
            </div>
          </div>

          <div class="col-md-6">
            <img src="static/images/pgg_4.jpg" alt="Image" class="img-fluid mb-4 rounded">
          </div>

          <div class="col-md-6">
            <h3>5 Trends ของ Software Development ในปี 2020</h3>
            <p class="text-muted">29/01/2020</p>
            <p>ยิ่งผ่านไปนานเท่าไร เทคโนโลยีก็ยิ่งก้าวหน้าไปมากยิ่งขึ้น และทุก ๆ ปีก็มักมีการคาดการณ์ต่าง ๆ เกี่ยวกับเทคโนโลยี ซึ่งส่วน</p>
            <div class="social mt-4">             
              <a href="https://www.techstarthailand.com/blog/detail/These-are-the-5-top-software-development-trends-for-2020/1170"><span class="icon-linkedin"></span></a>
            </div>
          </div>

          <div class="col-md-6">
            <img src="static/images/pgg_5.jpg" alt="Image" class="img-fluid mb-4 rounded">
          </div>

          <div class="col-md-6">
            <h3>เพิ่มทักษะการ Debug JavaScript Code ด้วยเทคนิคการใช้ Console</h3>
            <p class="text-muted">29/01/2020</p>
            <p>การใช้ Console เพื่อ Debug Code ของ JavaScript ถือเป็นอีกหนึ่งวิธีที่คุณสามารถทำได้ผ่าน Browsers ต่าง ๆ ซึ่งในบทความ</p>
            <div class="social mt-4">             
              <a href="https://www.techstarthailand.com/blog/detail/Boost-your-JavaScript-Debugging-Skills-With-These-Console-Tricks/1172"></span></a>
            </div>
          </div>
         
         
           
    </section>
     <section class="site-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 text-center" data-aos="fade">
          </div>
        </div>

        <div class="row align-items-center block__69944">

           
            </div>
          </div>
      </div>
    </section>
   
  </body>
</html>
{% endblock %}

templates/application.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


  <!-- HOME -->
  <section class="section-hero overlay inner-page bg-image" style="background-image: url('static/images/hero_1.jpg');" id="home-section">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1 class="text-white font-weight-bold"></h1>
          <div class="custom-breadcrumbs">
            <a href="#">Home</a> <span class="mx-2 slash">/</span>
            
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="site-section">{% if user.is_authenticated %}
    <div class="container">
      <form  enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col-lg-3">
          <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <img class="border p-1 d-inline-block rounded-circle" src="{{user.profile.image.url}}" width="200" height="200">&nbsp;&nbsp;
              <br> <br>
            <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Profile</a>
            <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Manage Job</a>
          </div>
        </div>

   
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>KRADAN IT</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="Free-Template.co" />
    <link rel="shortcut icon" href="ftco-32x32.png">
  
    
    <link href="https://fonts.googleapis.com/css?family=Athiti&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/quill.snow.css' %}">
    

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">    
 
  </head>
  <body id="top">

  <div id="overlayer"></div>
  <div class="loader">
    <div class="spinner-border text-primary" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>
    

<div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    

    <!-- NAVBAR -->
    <header class="site-navbar mt-3">
      <div class="container-fluid">
        <div class="row align-items-center">
          <div class="site-logo col-6"><a href="{% url 'post:index' %}">Kradan IT</a></div>

          <nav class="mx-auto site-navigation">
            <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
              <li><a href="{% url 'post:index' %}" class="nav-link active">Home</a></li>
              <li><a href="{% url 'post:about' %}">About</a></li>
              <li class="has-children">
                <a href="">Find Job</a>
                <ul class="dropdown">
                  <li><a href="{% url 'post:FindJob' %}">Find job by yourself</a></li>
                </ul>
              </li>
              {% if user.is_authenticated%}
              <li class="has-children">
                <a href="">Employment</a>
                <ul class="dropdown">
                  <li><a href="{% url 'company_profile' %}">Company Profile</a></li>
                  <li><a href="{% url 'post:createPost'%}">Add a new job</a></li>
                </ul>
              </li>   
              {% endif %}          
              <li><a href="{% url 'post:contact' %}">Contact us</a></li>
              <li class="d-lg-none"><a href="{% url 'register' %}">Register</a></li>
              <li class="d-lg-none"><a href="{% url 'login' %}">Log in</a></li>
            </ul>
          </nav>

          {% if user.is_authenticated %}
          <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
            <div class="ml-auto"></div>
            <a href="{% url 'profile' %}" class="btn btn-primary  text-white btn-user"><span class="icon-user icon mr-2"></span>Hello.. {{user.username}}</a>&nbsp;&nbsp;
            <a href="{% url 'logout' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Log out</a>
          {% else %}
          <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
            <div class="ml-auto">
              <a href="{% url 'register' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Register</a>
              <a href="{% url 'login' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Log in</a>
            </div>
          {% endif %}
            <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
          </div>

        </div>
      </div>
    </header>
    {% block content %}

    {% endblock %}
      
      <!-- SCRIPTS -->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
      <script src="{% static 'js/stickyfill.min.js' %}"></script>
      <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
      <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
      
      <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
      <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
      <script src="{% static 'js/owl.carousel.min.js' %}"></script>
      
      <script src="{% static 'js/bootstrap-select.min.js' %}"></script>
      
      <script src="{% static 'js/quill.min.js' %}"></script>

      <script src="{% static 'js/custom.js' %}"></script>    
</body>
</html>

templates/com_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block content %}
<link href="https://fonts.googleapis.com/css?family=Prompt&display=swap" rel="stylesheet">

<style>
h1 {
  font-family: Prompt ;
}

</style>


 <!-- HOME -->
 <section class="section-hero overlay inner-page bg-image" style="background-image: url('static/images/hero_1.jpg');" id="home-section">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1 class="text-white font-weight-bold">Company Profile</h1>
          <div class="custom-breadcrumbs">
            <a href="#">Home</a> <span class="mx-2 slash">/</span>
            <a href="#">Job</a> <span class="mx-2 slash">/</span>
            <span class="text-white"><strong>Company Profile</strong></span>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="site-section">{% if user.is_authenticated %}
    <div class="container">
      <form action="{% url 'editcompany' id=user.id %}" enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col-lg-3">
          <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <img class="border p-1 d-inline-block rounded-circle" src="{{user.companyprofile.com_img.url}}" width="200" height="200">&nbsp;&nbsp;
              <br> <br>
            <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Profile</a>
            <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Manage Job</a>
          </div>
        </div>

        <div class="col-lg-9">
          <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
               <div class="row">  
                <div class="col-sm-12">  
              
                    <div class="form-group">
                        <h6 for="">ชื่อบริษัท</h6>
                        <input type="text" name="company_name" class="form-control" value="{{user.companyprofile.company_name}}" >
                    </div>

                    <div class="form-group">
                        <h6 for="">รายละเอียดบริษัท</h6>
                        <textarea class="form-control" rows="5" id="company_detail" name="company_detail">{{user.companyprofile.company_detail}}</textarea>
                    </div>

                    <div class="form-group">
                        <h6 for="">ที่อยู่บริษัท</h6>
                         <textarea class="form-control" rows="5" id="company_address" name="company_address">{{user.companyprofile.company_address}}</textarea>
                    </div>

                    <div class="form-group">
                        <h6 for="">Upload Profile</h6>
                        <input type='file' name="img" class="form-control" value="{{user.companyprofile.com_img.url}}" >
                    </div>
               
                    <button type="submit" class="btn btn-primary">บันทึก</button>
                </div>
            </div>
          </form>
      </div>

            <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
              <table class="table table-hover">
                  <thead>
                  <tr>
                    <th>title</th>
                    <th>Type_Job</th>
                    <th>Applicant</th>
                    <th>Date_posted</th>
                    <th>Manage</th>
                    <th></th>
                  </tr>
                </thead>
                {% for i in post %}{% if i.user == user %}
                  <tr> 
                      <td>{{i.title}}</td>
                      <td>{{i.type_job}}</td>
                      <td>{{i.post.all.count}}</td>
                      <td>{{i.date_posted|date:"F d, Y"}}</td>
                          
                      <td> <a class="btn btn-sm btn" href="{% url 'post:update_post' i.id %}">
                        <i class="icon-cog"></i> Edit</a></td>

                      <td><a class="btn btn-sm btn-danger" href="{% url 'post:delete_post' i.id %}">Delete</a></td>

                  </tr> {% endif %}
                  {% endfor %}
                </table>
                  <a class="btn btn-primary  btn-sm btn-block" href="{% url 'post:createPost' %}">Create Post</a>
            </div>
          </div>
        </div>

        </div>
      </div>
    </div>
  {% else %}
  <div class="container">
  <div class="row">
  <h1>เข้าสู่ระบบ</h2>
  </div>
  </div>
  {% endif %}
  </section>
 
  
  {% endblock content %}

templates/delete.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>KRADAN IT</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="Free-Template.co" />
    <link rel="shortcut icon" href="ftco-32x32.png">

    <link href="https://fonts.googleapis.com/css?family=Athiti&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/quill.snow.css' %}">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">    
  </head>
<body>
<br>
<div class="row">
	<div class="col-md-12">
		<div class="card card-body">


			<p>Are you sure you want to delete "{{item}}"?</p>

			<form action="{% url 'post:delete_post' item.id  %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'company_profile' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm" value="Confirm">
			</form>
		</div>
	</div>
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<style>
input[type=text], select {
  width: 23%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
</style>

<!-- HOME -->
    <section class="home-section section-hero overlay bg-image" style="background-image: url('static/images/hero_1.jpg');" id="home-section">

      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-12">
            <div class="mb-5 text-center">
              <h1 class="text-white font-weight-bold">IT JOBS BOARD</h1>
              <p>At Sountern</p>
            </div>
            <form method="get" class="search-jobs-form">
            {{myFilter.form}}
              <button type="submit" class="btn btn-primary "><span class="icon-search icon mr-2"></span>Find Job</button>
            </form>
          </div>
        </div>
      </div>

      <a href="#next" class="scroll-button smoothscroll">
        <span class=" icon-keyboard_arrow_down"></span>
      </a>

    </section>
    
    
    <section class="site-section">
      <div class="container">

        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2">{{ posts.count }} Job Listed</h2>
          </div>
        </div>
        {% for i in post %}
        <ul class="job-listings mb-5">
          <li class="job-listing d-block d-sm-flex pb-3 pb-sm-0 align-items-center">
            <a href="{% url 'post:post_detail' i.id  %}"></a>
            <div class="job-listing-logo"> {% if i.user == user %}
              <img class="border p-1 d-inline-block rounded" src="{{user.companyprofile.com_img.url}}" width="200" height="200">
              {% else %} 
              <img class="border p-1 d-inline-block rounded" src="{{i.user.companyprofile.com_img.url}}" width="200" height="200">    
              {% endif %}
            </div>

            <div class="job-listing-about d-sm-flex custom-width w-100 justify-content-between mx-4">
              <div class="job-listing-position custom-width w-50 mb-3 mb-sm-0">
                <h2>{{ i.title }} </h2><br>
              </div>
              <div class="job-listing-location mb-3 mb-sm-0 custom-width w-25">
                <span class="icon-room"></span>{{ i.date_posted|date:"F d, Y"}}<br>
                <h6 class="text-danger"> {{ i.timestamp|timesince }} ago</h6>
              </div>
              <div class="job-listing-meta">
                <span class="badge badge-danger">{{ i.type_job }}</span>
              </div>
              <div class="job-listing-meta">
                <span class="badge badge-primary">{{ i.location }}</span>
              </div>
            </div>
          </li>
          {% endfor %}
      
        
        

        <div class="row pagination-wrap">
          <div class="col-md-6 text-center text-md-left mb-4 mb-md-0">
            <span>Showing 1-7 Of 43,167 Jobs</span>
          </div>
          <div class="col-md-6 text-center text-md-right">
            <div class="custom-pagination ml-auto">
              <a href="#" class="prev">Prev</a>
              <div class="d-inline-block">
              <a href="#" class="active">1</a>
              <a href="#">2</a>
              <a href="#">3</a>
              <a href="#">4</a>
              </div>
              <a href="#" class="next">Next</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    

    <section class="site-section services-section bg-light block__62849" id="next-section">
      <div class="container">
        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2">Find Job By Position</h2>
          </div>
        </div>
        
        <div class="row">        
        
          <div class="col-6 col-md-6 col-lg-4 mb-4 mb-lg-5">
            
            <a href="service-single.html" class="block__16443 text-center d-block">
              <span class="custom-icon mx-auto"><span class="icon-magnet d-block"></span></span>
              <h3>Graphic design</h3>             
            </a>

          </div>
          <div class="col-6 col-md-6 col-lg-4 mb-4 mb-lg-5">
            
            <a href="service-single.html" class="block__16443 text-center d-block">
              <span class="custom-icon mx-auto"><span class="icon-trophy d-block"></span></span>
              <h3>Information security</h3>              
            </a>            

          </div>
          <div class="col-6 col-md-6 col-lg-4 mb-4 mb-lg-5">
            
            <a href="service-single.html" class="block__16443 text-center d-block">
              <span class="custom-icon mx-auto"><span class="icon-laptop d-block"></span></span>
              <h3>Information system </h3>             
            </a>            

          </div>
          <div class="col-6 col-md-6 col-lg-4 mb-4 mb-lg-5">
            
            <a href="service-single.html" class="block__16443 text-center d-block">
              <span class="custom-icon mx-auto"><span class="icon-search d-block"></span></span>
              <h3>Software / Programming</h3>             
            </a>

          </div>
          <div class="col-6 col-md-6 col-lg-4 mb-4 mb-lg-5">
            
            <a href="service-single.html" class="block__16443 text-center d-block">
              <span class="custom-icon mx-auto"><span class="icon-paper-plane d-block"></span></span>
              <h3>Consultant</h3>            
            </a>

          </div>
          <div class="col-6 col-md-6 col-lg-4 mb-4 mb-lg-5">
            
            <a href="service-single.html" class="block__16443 text-center d-block">
              <span class="custom-icon mx-auto"><span class="icon-plug d-block"></span></span>
              <h3>IT support</h3>             
            </a>

          </div>
          
          <div class="col-6 col-md-6 col-lg-4 mb-4 mb-lg-5">

            <a href="service-single.html" class="block__16443 text-center d-block">
              <span class="custom-icon mx-auto"><span class="icon-magnet d-block"></span></span>
              <h3>Network</h3>             
            </a>

          </div>
          <div class="col-6 col-md-6 col-lg-4 mb-4 mb-lg-5">
            
            <a href="service-single.html" class="block__16443 text-center d-block">
              <span class="custom-icon mx-auto"><span class="icon-trophy d-block"></span></span>
              <h3>Database</h3>              
            </a>            

          </div>
          <div class="col-6 col-md-6 col-lg-4 mb-4 mb-lg-5">
            
            <a href="service-single.html" class="block__16443 text-center d-block">
              <span class="custom-icon mx-auto"><span class="icon-laptop d-block"></span></span>
              <h3>Test Systems</h3>             
            </a>            

          </div>
          <div class="col-6 col-md-6 col-lg-4 mb-4 mb-lg-5">
            
            <a href="service-single.html" class="block__16443 text-center d-block">
              <span class="custom-icon mx-auto"><span class="icon-search d-block"></span></span>
              <h3>Hardware</h3>             
            </a>

          </div>
          <div class="col-6 col-md-6 col-lg-4 mb-4 mb-lg-5">
            
            <a href="service-single.html" class="block__16443 text-center d-block">
              <span class="custom-icon mx-auto"><span class="icon-paper-plane d-block"></span></span>
              <h3>Mobile application</h3>            
            </a>

          

          </div>
        </div>
      </div>
    </section>
  </body>
</html>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

    <!-- HOME -->
    <section class="section-hero overlay inner-page bg-image" style="background-image: url('static/images/hero_1.jpg');" id="home-section">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h1 class="text-white font-weight-bold">Login</h1>
            <div class="custom-breadcrumbs">
              <a href="#">Home</a> <span class="mx-2 slash">/</span>
              <span class="text-white"><strong>Log In</strong></span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="site-section">
        <div class="container">
          <div class="row">
            <div class="col-lg-6 mb-5">
              <h2 class="mb-4">Login</h2>

              <form action="login" method="POST" class="p-4 border rounded">
                  {% csrf_token %}
                <div>
                    {% for messages in messages %}
                    <span class="badge badge-danger">{{ messages }}</span>
                    {% endfor %}
                </div>
                <div class="row form-group">
                  <div class="col-md-12 mb-3 mb-md-0">
                    <label class="text-black" for="fname">Username</label>
                    <input type="text" name= "username" id="fname" class="form-control" placeholder="Username">
                  </div>
                </div>
                
                <div class="row form-group mb-4">
                  <div class="col-md-12 mb-3 mb-md-0">
                    <label class="text-black" for="fname">Password</label>
                    <input type="password" name= "password" id="fname" class="form-control" placeholder="Password">
                  </div>
                </div>
  
                <div class="row form-group">
                  <div class="col-md-12">
                    <input type="submit" value="Log In" class="btn px-4 btn-primary text-white">
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>
        
    </body>
  </html>
  {% endblock %}